# Generated by Django 4.2.3 on 2023-08-01 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mobile',
            name='slug',
        ),
    ]
