# Generated by Django 4.2.3 on 2023-08-01 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_remove_mobile_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobile',
            name='slug',
            field=models.SlugField(max_length=255, null=True),
        ),
    ]
