# Generated by Django 4.2.3 on 2023-08-07 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_mobile_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobile',
            name='photo',
            field=models.ImageField(null=True, upload_to='', verbose_name='Фото'),
        ),
        migrations.AddField(
            model_name='mobile',
            name='quantity',
            field=models.IntegerField(null=True, verbose_name='Кол-во'),
        ),
        migrations.AlterField(
            model_name='mobile',
            name='description',
            field=models.CharField(max_length=255, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='mobile',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='mobile',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='mobile',
            name='slug',
            field=models.SlugField(max_length=255),
        ),
    ]
