# Generated by Django 4.2.3 on 2023-08-07 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_mobile_photo_mobile_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobile',
            name='photo',
            field=models.ImageField(upload_to='', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='mobile',
            name='quantity',
            field=models.IntegerField(verbose_name='Кол-во'),
        ),
    ]
