# Generated by Django 4.2.3 on 2023-08-07 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_mobile_photo_alter_mobile_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Firm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Фирма')),
            ],
        ),
        migrations.AlterModelOptions(
            name='mobile',
            options={'verbose_name': 'Мобильный телефон', 'verbose_name_plural': 'Мобильные телефоны'},
        ),
        migrations.AlterField(
            model_name='mobile',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Модель'),
        ),
        migrations.AddField(
            model_name='mobile',
            name='firm',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='shop.firm'),
        ),
    ]
