# Generated by Django 4.2.3 on 2023-08-09 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_firm_alter_mobile_options_alter_mobile_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='firm',
            options={'verbose_name': 'Фирма', 'verbose_name_plural': 'Фирмы'},
        ),
        migrations.AlterField(
            model_name='mobile',
            name='firm',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='shop.firm', verbose_name='Фирма'),
        ),
    ]
